language: python
env:
  global:
    - secure: m+cuI6p0W3rA+cPS1y9gOkM0ArjFgwZ56QrpA1C6YRCS2cPKjp7gG6qYKXKM+8qinuYZzmRf9ecQzPXGla3i1q7cSBdk0/wZp5THBmJNsZ9OjdOeP9AkKaA3FNXpqpJzeExPLP4h4Xn6H32VADn4lVgTOLhN7aGfMftiR+3/2waXfl6Q/eT3GL5GBfpyTf7hKW2veXNYTNArJn+SRoPP6yM521a9aza92IhKqwYM+X5Z8MpzCqW+62LbZtOKMW4YsVwcgw7yYNf5cZiLGR+WZtBuTIb8LOJ0zKfhz05O4SGhVp8ErzyGhndnG7w4PirBn5xbthUFqyVuokLngMdpAv/3g5X+MZvrBEU9esXNRvMYgYhBBaWES5lbu3saNJlt9306jBGntbnQvJrH1Bx1WIbwQZgxRthtDrxEzxjiV5NTwUQCSzgT04B/D3iZAoUhPFiDmr/0WEurGFCnthvY/XNgMlQOxHe7kFsn0FnlEPvkcFTy5zSeXvCowWL+6dwvedVH352bZVI3e+vQ7fYgBK8ETz8kMYixnFKSiq4wms/2bNrI/1a4eCuviJTsSvYN5iUZVQRQEc7BUca2kgPFG0ss/B3iCmaNOzzixt1Ok/4D8rJiejcgezQ2amwcoiwOTlJNNi7AXyKsOIZ1Jr0q0p6KdUOz1nzTlRYYGLwzfgM=
python:
  - '2.7'
  - '3.4'
  - '3.5'
  - '3.6'
install:
  - pip install .
before_script:
  - pip install pytest pytest-mock coverage
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - coverage run --source=dbcl -m pytest -v && coverage xml
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
notifications:
  slack:
    secure: N8DefnqbMqvRw7FJtQa4BEBeSt3SP6Z38kzQ9/V2z6Q/Sj04bdBrCH9xrAmRzquUOpkj8ONTf5Y+kYenenFQeVlW1Qx2KDHkKZedn2FZ4mC5FHhuf7nM7Ha5YGxsXff2hKZfvbXtXoT3EuIOn/3uC/POLDu80ttNOBNYgDizzoExr516CgU1+b5pbXyGTF4CROxdRWs1XU5iWigDqQsAxLQ+Z14usMkfOn5nPEMHmLfEB+gAx35tmOSx3u888iYNYIcl4c8HUeEwhjQqMfiJFSHMQuGjMhhIxkUoT0944NR02AULeglIOMW7z+FPAQeBbeGMEWw1AITYuGOeAazbw8aKrha+hHBqVdL4AEYxzYblmv25XfSudxnQRHLPiOtCyY8bRioy/0FTIKCCBKuVPGc2ee10QUrpWvAfLRONI4nMIQCVBh5XDt4l/G6RxZ3HZC2lwzp9rePzxeK4S1Tz+JGohZ0t6A/VB7vQaorn5CwY8CWiJ6mW8xrkmcNR0Gnnyfw4K9nXYM1FO41HZX+j3ZXnJAx02Jl14U6n/BDUU7ocnk5E3ewlfy7KdWy6oMvj2bDXcTRfXzxo1EvRvEW7+9H5Dt4sOO2STn8lXaTq4e+gD3+mgGoL5XZJk493vh6e9Xolkd+FzQiCnIjAcJX3Bv6zpblYXp5f0T9wi+l/ygw=
deploy:
  provider: pypi
  user: ksofa2
  password:
    secure: "kIz9evfqHV6Pi69txDD54h/QwCcquRJS7dfhCC4nHOMjSJinSJwBlxK273EgPOSyMNoFH/8dWxN8RkAXy5NzYZpiiptUwVaOqC4qLZs0Gz+ufJ0ztP1/dO7t+gNEl0WJDwqkAfvF2vbOJYFy4hr8nRYFYeZZo+xnxjRoCSarIIb49KHf6P0AjeoJnvHB2a94bY6CnrTAAMfclGE/WFo6yhYf1AmFaW+JtBySxwXu1tiRO30UL3L9iwH8hDWwLhna1YhcW4d1Lyb4i500XUsZWW+kDLywO5gdkFN6qFaRtnu0yKGZH1TP27D6xyLk8My8q1BNEHXjxUlbw1hSqzqAFfelVB9ZZpcIFy9gjMwgSwgXXACM515bI7xFxpJL4djzR1yuZyYWWIGxEljMTg0aedIIyVVjk5nn6+0oUtPTTinelgEAI2i7w08OMdn+ogLxpvRFqTjxKrhSfmMNJjcMDeLiyM+LkJ0r4tHivmtTW2FMDivmUDFtInepWpo9Y2Ms3QswdziSPMJxOkJxL9EefmOGtWmiL9Ue6x8DZYcqYN63e6raWGCqLjY9WYn9+Fy+Wkiw1wd1OVJG3uHRtxl7BkFsHpZoEFH5/TwecAKlCEE7RSJg7ZBdtOAVEVfDvzJ6MaXXAPaXL2/WMkECQQAq0I7lYqgPPCantwrRcqzO5JQ="
  on:
    tags: true
