language: python
env:
  global:
    - secure: m+cuI6p0W3rA+cPS1y9gOkM0ArjFgwZ56QrpA1C6YRCS2cPKjp7gG6qYKXKM+8qinuYZzmRf9ecQzPXGla3i1q7cSBdk0/wZp5THBmJNsZ9OjdOeP9AkKaA3FNXpqpJzeExPLP4h4Xn6H32VADn4lVgTOLhN7aGfMftiR+3/2waXfl6Q/eT3GL5GBfpyTf7hKW2veXNYTNArJn+SRoPP6yM521a9aza92IhKqwYM+X5Z8MpzCqW+62LbZtOKMW4YsVwcgw7yYNf5cZiLGR+WZtBuTIb8LOJ0zKfhz05O4SGhVp8ErzyGhndnG7w4PirBn5xbthUFqyVuokLngMdpAv/3g5X+MZvrBEU9esXNRvMYgYhBBaWES5lbu3saNJlt9306jBGntbnQvJrH1Bx1WIbwQZgxRthtDrxEzxjiV5NTwUQCSzgT04B/D3iZAoUhPFiDmr/0WEurGFCnthvY/XNgMlQOxHe7kFsn0FnlEPvkcFTy5zSeXvCowWL+6dwvedVH352bZVI3e+vQ7fYgBK8ETz8kMYixnFKSiq4wms/2bNrI/1a4eCuviJTsSvYN5iUZVQRQEc7BUca2kgPFG0ss/B3iCmaNOzzixt1Ok/4D8rJiejcgezQ2amwcoiwOTlJNNi7AXyKsOIZ1Jr0q0p6KdUOz1nzTlRYYGLwzfgM=
python:
  - '2.7'
  - '3.4'
  - '3.5'
  - '3.6'
install:
  - pip install .
before_script:
  - pip install pytest pytest-mock coverage
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - coverage run --source=dbcl -m pytest -v && coverage xml
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
notifications:
  slack:
    secure: N8DefnqbMqvRw7FJtQa4BEBeSt3SP6Z38kzQ9/V2z6Q/Sj04bdBrCH9xrAmRzquUOpkj8ONTf5Y+kYenenFQeVlW1Qx2KDHkKZedn2FZ4mC5FHhuf7nM7Ha5YGxsXff2hKZfvbXtXoT3EuIOn/3uC/POLDu80ttNOBNYgDizzoExr516CgU1+b5pbXyGTF4CROxdRWs1XU5iWigDqQsAxLQ+Z14usMkfOn5nPEMHmLfEB+gAx35tmOSx3u888iYNYIcl4c8HUeEwhjQqMfiJFSHMQuGjMhhIxkUoT0944NR02AULeglIOMW7z+FPAQeBbeGMEWw1AITYuGOeAazbw8aKrha+hHBqVdL4AEYxzYblmv25XfSudxnQRHLPiOtCyY8bRioy/0FTIKCCBKuVPGc2ee10QUrpWvAfLRONI4nMIQCVBh5XDt4l/G6RxZ3HZC2lwzp9rePzxeK4S1Tz+JGohZ0t6A/VB7vQaorn5CwY8CWiJ6mW8xrkmcNR0Gnnyfw4K9nXYM1FO41HZX+j3ZXnJAx02Jl14U6n/BDUU7ocnk5E3ewlfy7KdWy6oMvj2bDXcTRfXzxo1EvRvEW7+9H5Dt4sOO2STn8lXaTq4e+gD3+mgGoL5XZJk493vh6e9Xolkd+FzQiCnIjAcJX3Bv6zpblYXp5f0T9wi+l/ygw=
deploy:
  provider: pypi
  user: ksofa2
  password:
    secure: P9xD6aPSRk4wFNrv6iVn6RK/sx8Sn1iGGPBIo5IVJ1HdPUbYkilsgMaWYKUS22MQRsuOPBpxBvIPxWy/0GUJ/rVTfAnb0EQ+EO3r38wjROk+TS0p1ASHu9C8wQmrO5X4dvJ8dqQ9EKvfqM8qMylORLUs8E60rSKYrAqC3nj4o7LCSB+g0jx+IvXyp+x3mGP3C4OzbFTk11NBcpaiYDS4X0aPUmXsWvvMB3lQstS8LyoM7PQ6i1yOOPW77jlShQ8tJa3c/Tv0j+ZnD3j7wSeXkHdQuP6iHbAdu0TsSD/vUnlaDg7bpQFioMNXwPLUmb2WNgxGXiQin1abXUTpmThXsHS0cuRloAn3Dh+3V1GvEp1Z1QBPdGA8QU0f/EVm7hf0K25iOyPLhf4v9vCqJ/INn14am8FYCWPZMooNStphYdfHvGcM7UJvTE76266OSnsq93HYj2PxIh8wdhmzTUcBey+5gTdo9eVzhrwpPUKlOqsVWnnlhmx0LsysBgzHAInguf6dJwI98FUcS4k2rsVarWNPJwgWll9/TPTrksjjH/ptXLvCwoIlw/9fEZjmM0YourjwtTIAeLfcdEbJa85x4E2XIBJqkXWoRYd18esdWpQBd8ffQ+vAwaHd9hT8hHCKBivulnk8UHHcfM84510PFMgGMoNDQAN3qude709J+Jw=
  on:
    tags: true
